# thaw_script_config.ini
#
# Copyright (C) 2015-2024 Vas Vasiliadis
# University of Chicago
#
# Results thaw utility configuration
# For use with thaw_script.py
# ** Remember to first read config from util_config.ini for default values
#
##

# AWS SNS Settings
[sns]
ThawTopic = ${CnetId}_a17_thaw_topic
GlacierRestoreTopic = arn:aws:sns:us-east-1:127134666975:${CnetId}_a17_glacier_restore

# AWS Glacier Settings
[glacier]

# AWS SQS Settings
[sqs]
ThawQueueName = ${CnetId}_a17_thaw_queue

### EOF
