# annotator_config.ini
#
# Copyright (C) 2015-2023 Vas Vasiliadis
# University of Chicago
#
# GAS annotator configuration
#
##

[DEFAULT]
CnetId = jfpan01

# GAS parameters
[gas]
AnnotationsTable = ${CnetId}_annotations

# AnnTools settings
[ann]
JobsDirectory = ~/gas/ann/jobs
RunScript = ~/gas/ann/run.py

# AWS general settings
[aws]
AwsRegionName = us-east-1

# AWS S3 settings
[s3]
InputsBucketName = gas-inputs
ResultsBucketName = gas-results
KeyPrefix = ${CnetId}/

# AWS SNS settings
[sns]
JobResultsTopic = ${CnetId}_a17_job_results
ArchiveTopic = ${CnetId}_a17_archive_topic

# AWS SQS Settings
[sqs]
JobRequestsQueueName = ${CnetId}_a17_job_requests
WaitTime = 20
MaxMessages = 10
VisibilityTimeout = 60

# Job status values
[job_status]
Pending = PENDING
Running = RUNNING
Completed = COMPLETED
Error = ERROR

### EOF
