# archive_script_config.ini
#
# Copyright (C) 2015-2024 Vas Vasiliadis
# University of Chicago
#
# Results archive utility configuration for use with archive_script.py
# ** Remember to first read config from util_config.ini for default values
#
##

# AWS SQS Settings
[sqs]
ArchiveQueue = ${CnetId}_a17_archive_queue

# SNS settings
[sns]
ArchiveTopic = ${CnetId}_a17_archive_topic

# Archive settings
[archive]
DelaySeconds = 180

### EOF
